# fly.toml - configuration for Fly.io deployment

app = "spot-qr-coupons"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  # Use Buildpacks for a Python/Flask app
  builder = "paketobuildpacks/builder:base"

[env]
  # POINT your DATA_DIR at the mounted volume
  DATA_DIR = "/data"

# Define a persistent volume named "data" and mount it at /data
[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  # HTTP on port 80
  [[services.ports]]
    handlers = ["http"]
    port = 80

  # HTTPS on port 443
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # Optional: manage max concurrent connections
  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  # Health checks over TCP
  [services.tcp_checks]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
